version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install -r Requirements.txt -t lib
  build:
    - echo "Zipping deployment package..."
    - cd lib
    - zip -r9 ../deployment package.zip
    - cd ..
    - zip -g deployment package.zip s3DailyJsonRawDataProcessing.py
  post_build:
    - echo "Uploading to s3"
    - aws cp deployment package.zip s3://lambda-builds-zip-59544/
    - echo "Updating lambda function via s3..."
    - aws lambda update-function-code --function-name github-to-lambda-CICD --s3-bucket lambda-builds-zip-59544 --s3-key deployment package.zip
    - echo "Uploading to s3"
